language: scala
services: mysql
before_script:
  - mysql -e 'create database communityRoots;'
  - mysql -e 'create table User;'
script:
 - "cd $TRAVIS_BUILD_DIR"
 - "sbt ++$TRAVIS_SCALA_VERSION test"
notifications:
  email: false
